# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.5.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 76650075+Toffy13@users.noreply.github.com
author_name: Marco Francesco Toffaldano
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: Prova-contracts

